last_parsed_obj_H_path: "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/last_parsed_obj_for_first_run.pkl"
CT_fundamentals_path: "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/fundamental_final_draft.csv"
CT_parquet_file_path:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/"
CT_legacy_parquet_file_path: "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_legacy_data_staging/"
CT_parsed_parquet_file:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/CT_parsed_df.parquet"
CT_preprocessed_parquet_file:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/CT_preprocessed_df.parquet"
CT_TOPICX_parquet_file:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/CT_topicx_df.parquet"
CT_FINBERT_parquet_file:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/CT_FINBERT_df.parquet"
CT_sentiment_parquet_file: "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/CT_data_staging/CT_sentiment_df.parquet"
dbfs_resource_path:  "/FileStore/{0}/resources/"
dbfs_prefix:  "/dbfs"
model_artifacts_path: "/dbfs/mnt/access_work/UC25/Libraries"
model_address:  "/dbfs/mnt/access_work/UC25/Libraries/HuggingFace/finbert-sentiment"
CT_legacy_last_parsed_obj_path:  "/dbfs/mnt/access_work/CallTranscriptPipelines/fundamentals/Quant_Stg/last_parsed_obj/last_parsed_obj_stg3.pkl"
preprocessing_words_path:  "/LM_Dictionary/"
folder_name: sunil