paths:
  model_folder: "/dbfs/mnt/access_work/UC25/Libraries/HuggingFace/"
  output_parquet: "/dbfs/mnt/access_work/UC25/Topic_Modeling/NLI_Models/MASS_Labor/Backtest/MASS_Labor_Macro_historical_test.parquet"
  class_data: "/dbfs/mnt/access_work/UC25/Topic_Modeling/NLI_Models/"

snowflake:
  db: "EDS_PROD"
  schema: "QUANT"

dask:
  n_workers: 8
  threads_per_worker: 1

logging:
  file_path: "logs/app.log"

model:
  folder_name: "deberta-v3-large-zeroshot-v2"
  device: ${oc.env:DEVICE, 0}