CT_FINBERT_label_columns: quant/table_columns_names/CT_FINBERT_label_columns.csv
CT_legacy_aggregate_text_list: quant/table_columns_names/CT_legacy_aggregate_text_list.csv
CT_legacy_drop_columns_list: quant/table_columns_names/CT_legacy_drop_columns_list.csv
CT_legacy_final_CT_output_columns: quant/table_columns_names/CT_legacy_final_CT_output_columns.csv
CT_legacy_FINBERT_DF_merge_on_columns: quant/table_columns_names/CT_legacy_FINBERT_DF_merge_on_columns.csv
CT_legacy_FINBERT_drop_columns_list: quant/table_columns_names/CT_legacy_FINBERT_drop_columns_list.csv
CT_legacy_NLP_DF_merge_on_columns: quant/table_columns_names/CT_legacy_NLP_DF_merge_on_columns.csv
CTS_combined_scores_columns: quant/table_columns_names/CTS_combined_scores_columns.csv
CTS_FINBERT_labels_columns: quant/table_columns_names/CTS_FINBERT_labels_columns.csv
CTS_FINBERT_labels_columns_drop: quant/table_columns_names/CTS_FINBERT_labels_columns_drop.csv
CTS_FINBERT_specific_scores_columns: quant/table_columns_names/CTS_FINBERT_specific_scores_columns.csv
discussion_labels: quant/table_columns_names/discussion_labels.csv
FILT_sections: quant/table_columns_names/FILT_sections.csv