queries:
  READ_QUERY: |
    SELECT 
      CALL_ID,
      ENTITY_ID,
      DATE,
      FILT_MD,
      FILT_QA,
      SENT_LABELS_FILT_MD,
      SENT_LABELS_FILT_QA,
      CALL_NAME,
      COMPANY_NAME,
      EARNINGS_CALL,
      ERROR,
      TRANSCRIPT_STATUS,
      UPLOAD_DT_UTC,
      VERSION_ID,
      EVENT_DATETIME_UTC,
      PARSED_DATETIME_EASTERN_TZ
    FROM 
      QUANT_LIVE.CTS_FUND_COMBINED_SCORES_H t2
    WHERE 
      NOT EXISTS (
        SELECT 1 
        FROM EDS_PROD.QUANT.YUJING_MASS_LABOR_MACRO_DEV_2 t1
        WHERE 
          t1.CALL_ID = CAST(t2.CALL_ID AS VARCHAR(16777216)) 
          AND t1.ENTITY_ID = t2.ENTITY_ID 
          AND t1.VERSION_ID = t2.VERSION_ID
      )
    ORDER BY 
      PARSED_DATETIME_EASTERN_TZ DESC;